scientific-python/upload-nightly-action

README.md

Resolves #9 
Use of `--index-url` for the nightly package index and `--extra-index-url` for [public PyPI](https://pypi.org/) makes the behavior of installation precedence more explicit.
c.f. https://github.com/matplotlib/matplotlib/pull/22752 for discussion of relevance.
Also provide a very short summary of how `--index-url` takes priority over `--extra-index-url` to ensure that if a target package exists on the nightly package index it will be used over a version that exists on public PyPI.
(I'm tagging everyone who is already listed as a contributor to this repo so far for review)

DOC: Use scientific-python-nightly-wheels for nightly build index

---

README.md

Resolves #7 
* For security best practices, advocate that users of the action use it from known commit shas that correspond to tagged releases.
* Advocate that users use a Dependabot config file to update the action on new tags. This will bump the commit sha and also bump the release tag in the comment of the commit sha.

DOC: Advocate for using action from tagged release commit shas

---

README.md

The previous approach works with mamba and conda, but not with micromamba. So this adds `pip` back as an explicit dependency, before configuring pip installation flags.

In `environment.yaml`, add pip as dependency before configuring flags

---

.github/dependabot.yml
.github/workflows/remove-wheels.yml

Resolves #4
Remove all but the last `N_LATEST_UPLOADS` (defaulted to `5`) package version uploads to the package index to ensure space. To do this, reply on the output form of `anaconda show` to be able to filter on the item delimiter character sequence for each version currently uploaded.
As an explicit example:
```console
$ anaconda show scientific-python-nightly-wheels/xarray
Using Anaconda API: https://api.anaconda.org
Name:    xarray
Summary: 
Access:  public
Package Types:  Standard Python
Versions:
+ 2023.5.1.dev2+gd8ec3a3f
+ 2023.5.1.dev5+gf96aca45
+ 2023.5.1.dev6+g69445c62
+ 2023.5.1.dev9+g609a9016
+ 2023.5.1.dev10+gf45eb733
+ 2023.5.1.dev11+gfcb81756
+ 2023.5.1.dev12+gb319d867
+ 2023.5.1.dev14+ge3db6164
To install this package with pypi run:
pip install -i …
```

CI: Add removal of old uploads

---

.github/workflows/keep-alive.yml

Resolves #17 
Run a cron job on a monthly basis that force pushes a commit to a `keep-alive` branch.
(There might be more interesting or intelligent ways to do this, but this works. Revisions welcome!)

CI: Add workflow to avoid scheduled workflows becoming disabled

---

.github/workflows/keep-alive.yml
.github/workflows/remove-wheels.yml

In follow up to https://github.com/scientific-python/upload-nightly-action/pull/18/files#r1225142853, use the commit hash for `peaceiris/actions-gh-pages` `v3.9.3`. To avoid nightly failures on the `.github/workflows/remove-wheels.yml` on forks, which lack access to
https://github.com/scientific-python/upload-nightly-action/blob/b1c5a48e464ab8a45a1899cfaefc21548923ee6d/.github/workflows/remove-wheels.yml#L74
restrict the workflow to run only on the main repository by requiring the owner be the `scientific-python` GitHub org.

MNT: Use commit hash and run only on main repository

---

.github/workflows/remove-wheels.yml
Dockerfile
entrypoint.sh

High level summary:
* Use micromamba for speed.
* Configure Docker image environment for shell environment stability.
* Explicitly set anaconda-client version for reproducibility and security. (This should ideally be a lock file but one thing at a time).

ENH: Use micromamba for speed and set anaconda-client version

---

README.md

* At some point urls were changed to use '-' over '_'.

DOC: Fix broken url to Scientific Python Development Guide

---

action.yml

* The latest repository tag is [`0.1.0`](https://github.com/scientific-python/upload-nightly-action/releases/tag/0.1.0) and so the action version metadata should reflect that as well.

MNT: Align version metadata with git tag

---

.github/workflows/ci.yml
tests/test_package/README.md
tests/test_package/pyproject.toml

Resolves #15 
* Add simplest example package to tests so that it can be built for upload to Anaconda cloud as a test of the action.
- Use `setuptools` as the build backend over something like `hatchling` given the simple nature of the `test-package` given that `anaconda-client` `v1.12.0` doesn't understand valid metadata from PEP 518 build backends other than `setuptools`. c.f. https://github.com/Anaconda-Platform/anaconda-client/issues/676
* Add CI GitHub Action workflow to test the functionality of the action as shown in the README.
https://github.com/scientific-python/upload-nightly-action/blob/4792bc241c0a689e41f0fc4bf0953f26b8324c7b/README.md?plain=1#L10-L17

CI: Add test workflow for action

---

.github/workflows/remove-wheels.yml

Resolves #31 
* Add curl and jq to environment requirements.
* Use output from the anaconda.org API to get latest upload time for each release of a package. If the upload date is older than 30 days add the package release for removal.
* Use anaconda.org API over anaconda-client CLI API to get package versions as easier to understand.
Running this now (with the remove step commented out) gives
```
```
With regards to why the `numpy` `v1.25.0rc1` and `scipy` `v1.10.1` distributions are missing a last uploaded date c.f. https://github.com/Anaconda-Platform/anaconda-client/issues/682#issuecomment-1677699898

CI: Remove package versions older than 30 days

---

.github/workflows/remove-wheels.yml
packages-ignore-from-cleanup.txt

This is to add a file to host the agreed upon exceptions for the cleanups. Neither the number version nor the date based cleanup will run for these.
CI is expected to fail as 
Fixes #34 
cc @mattip

ENH: adding list of packages to exclude from cleanup

---

README.md

* For stability provide the commit SHA (5fb764c5bce1ac2297084c0f7161b1919f17c74f) that corresponds to the [`0.2.0` tag](https://github.com/scientific-python/upload-nightly-action/releases/tag/0.2.0) for users to pin to.

DOC: Update action commit SHA to the 0.2.0 tag

---

README.md
action.yml
cmd.sh

This is a follow up and fixes #46
This PR goal is to allow other Scientific Python projects to use this github action.
Please, let me know what you think, and I will be happy to rename the variables if needed.
Thanks  
**Squash and merge commit**
```
* Add optional `anaconda_nightly_upload_organization` and
`anaconda_nightly_upload_labels` arguments to allow for packages
to be uploaded to custom registires with the GitHub Action.
* Add docs to README providing an example of how to upload to an
alternative registry.
```

ENH: Add optional `anaconda_nightly_upload_organization` argument

---

cmd.sh

Resolves #52 
* Use the correct shell variable "LABEL_ARGS" to pass the lable args to the `anaconda upload` command.
- Amends PR https://github.com/scientific-python/upload-nightly-action/pull/47
* Note that it is important that `${LABEL_ARGS}` is NOT quoted during shell parameter expansion, else it will be treated as a file path to anaconda upload and not an argument.
- e.g. This will trigger `File "--label main " does not exist` errors.

FIX: Use correct shell variable in upload

---

.github/workflows/ci.yml

Add test uploads for non-main label 'test' and for multiple labels in a comma seperated list to compliment the feature added in PR #47.
This is an example of things working as intended prior to the cleanup step removing the test package.

CI: Add test for uploads with multiple labels

---

cmd.sh

* As 'env' prints the entire environment this is a route to accidentally leak secrets into public logs. While GitHub properly screens secrets
e.g.
```
...
LANG=C.UTF-8
RUNNER_ARCH=X64
RUNNER_TEMP=/home/runner/work/_temp
INPUT_ANACONDA_NIGHTLY_UPLOAD_TOKEN=***
ACTIONS_RUNTIME_URL=https://pipelinesghubeus12.actions.githubusercontent.com/qHNE2myTV4smS5AnZY3ul8hK3jNsaMgPRnYT5KDbQp06Cln8tW/
CONDA_PROMPT_MODIFIER=(upload-nightly-action) 
...
```
it would be better to not provide a chance for something to go wrong.
* Amends 8f0394fd2aa0c85d7364a9958652e8994e06b23c

FIX: Remove environment print for security

---

README.md

* For stability provide the commit SHA (6e9304f7a3a5501c6f98351537493ec898728299) that corresponds to the 0.3.0 tag for users to pin to.

DOC: Update action commit SHA to the 0.3.0 tag

---

.github/dependabot.yml

* Group dependabot updates to reduce the number of PRs.
- c.f. sp-repo-review GH212: Require GHA update grouping https://learn.scientific-python.org/development/guides/gha-basic/#GH212

CI: Group dependabot updates

---

.github/workflows/ci.yml
cmd.sh
conda-lock.yml
environment.yml

Resolves #57 
* On Anaconda Cloud as of 2024-01-04, if a wheel is being uploaded to a package, but the package only has one wheel in it and is of the same name as the uploaded wheel, Anaconda Cloud will overwrite the file by _removing_ the file from the package index. However, when this happens it removes the entire package, and then the wheel that is in the process of being uploaded has no destination and the upload fails. To guard against this, ensure for each package that has a wheel being uploaded if:
- there is only one release for the package
- and only 1 file for that release
- and the upload target wheel has the same name as the file
- that the file (and so the package) is removed in advance of the
upload.
* To make filtering names and versions from wheels easier, add a …

fix: Guard against removing package while uploading to it

---

README.md

* For stability provide the commit SHA that corresponds to the 0.4.0 tag (95f7bf6a22281b8072fae929429dd0408f09ea63) for users to pin to.

DOC: Update action commit SHA to the 0.4.0 tag

---

README.md

* For stability provide the commit SHA that corresponds to the 0.5.0 tag (b67d7fcc0396e1128a474d1ab2b48aa94680f9fc) for users to pin to.

DOC: Update action commit SHA to the 0.5.0 tag

---

.github/workflows/remove-wheels.yml

Resolves #73 
To guard against invalid dates being viewed as being older than the removal threshold date (c.f. https://github.com/numpy/numpy/issues/25907#issuecomment-1973370318) first check that the upload date is YYYY-MM-DD formatted. If not, warn in the logs and skip the offending package.

ci: Require upload dates to be valid to schedule package for removal

---

.github/workflows/ci.yml

`python -m build --outdir ./dist tests/test_package` now creates `test_package-0.0.1.tar.gz` and `test_package-0.0.1-py3-none-any.whl` thus this PR fixes the spelling for the CI to pass.

CI: fix spelling of test package name

---

README.md

Address typo noticed in https://github.com/apache/arrow/issues/40216#issuecomment-2315175755.
Users of the action should generate an access token from their own Anaconda Cloud account, not from the Scientific Python organisation's account.

docs: Correct token url to user account

---

tests/test_package/pyproject.toml

* As the test project does not need any part of setuptools specific infrastructure, use hatchling as the build backend.
* This is possible now that https://github.com/anaconda/anaconda-client/issues/676 has been resolved. c.f. https://github.com/scientific-python/upload-nightly-action/pull/27 for more information.

TST: Use hatchling as build backend for test project

---

README.md

* For stability provide the commit SHA that corresponds to the 0.6.0 tag (ccf29c805b5d0c1dc31fa97fcdb962be074cade3) for users to pin to.

DOC: Update action commit SHA to the 0.6.0 tag

---

action.yml

I'm not sure, but I think with the change to composite action we need to also be specific about this repo's filepaths by using `GITHUB_ACTION_PATH` . I tried to use `0.6.0` downstream and I got an error `Failed to generate cache key: Error: ENOENT: no such file or directory, open 'pixi.lock'
```
* As the GitHub Action is being used in other workflows, it does not know the
local filepaths and so to have prefix-dev/setup-pixi find the lock file and
'pixi run' know where `upload_wheels.sh` is, the environmental variable
'GITHUB_ACTION_PATH' is used through the ${{ github.action_path }} context.
- c.f. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
```

FIX: Use $GITHUB_ACTION_PATH to locate pixi.lock for downstream users

---

action.yml

I missed this in https://github.com/scientific-python/upload-nightly-action/pull/96 but we need to be explicit while using `pixi run` too.
I was tripping into `could not find pixi.toml or pyproject.toml which is configured to use pixi` while on the `pixi run` step downstream.
I can use https://github.com/scipp/scipp/pull/3542 to test this outside of this repo. I'll ping here once that passes :)
```
* Provide '--manifest-path' option to 'pixi run' to ensure the environment is properly activated.
--manifest-path <MANIFEST_PATH>
The path to 'pixi.toml' or 'pyproject.toml'
```

MAINT: Need to be explicit with action path while using pixi run too

---

README.md

* For stability provide the commit SHA that corresponds to the 0.6.1 tag for users to pin to.

DOC: Update action commit SHA to the 0.6.1 tag

---

.github/workflows/ci.yml

This should address the testing flaws that @MridulS discovered in PRs #96 and #98.
* Don't rely on the action's `$GITHUB_ACTION_PATH` variable being the current directory during testing.

CI: Use a non-default path to run the upload action

---

.github/workflows/ci.yml

* Use the `astral-sh/setup-uv` GitHub Action to setup the latest `uv`.
- This GitHub Action can be left unpinned as it should be updated regularly.
* Use `uv tool run --from build pyproject-build` to run build as the PyPI project name is `build` but the executable it provides is named `pyproject-build`.
* Use `uv tool run twine` to run `twine`.
c.f. https://docs.astral.sh/uv/reference/cli/#uv-tool-run
```console
$ docker run --rm -ti python:3.12 bash
root@cfbfbb22a859:/# curl -LsSf https://astral.sh/uv/install.sh | sh
downloading uv 0.4.17 x86_64-unknown-linux-gnu
installing to /root/.cargo/bin
uv
uvx
everything's installed!
To add $HOME/.cargo/bin to your PATH, either restart your shell or run:
source $HOME/.cargo/env (sh, bash, zsh)
source $HOME/.cargo/env.fish (fish) …
```

CI: Use 'uv tool run' for build and twine

---

.github/workflows/ci.yml

* Use `pixi` to provide the runtime environment for removal of the `test-package` from the `scientific-python-nightly-wheels` channel.
* Use `prefix-dev/setup-pixi` to setup `pixi` with no environment created.
- Use `run-install: false` to setup `pixi` with no install.
* Use `pixi exec --spec` to create a temporary `pixi` environment with `anaconda-client` installed for the `anaconda remove` command.
```
$ pixi exec --help
Run a command in a temporary environment
Usage: pixi exec [OPTIONS] [COMMAND]...
Arguments:
[COMMAND]...
The executable to run
Options:
-s, --spec <SPECS>
Matchspecs of packages to install. If this is not provided, the
package is guessed from the command
```

CI: Use pixi for all stages of testing

---

README.md

* @martindurant has pointed out that Anaconda.org credentials are needed, not Anaconda Cloud credentials.

DOC: Clarify service is Anaconda.org

---

action.yml
pixi.lock
pixi.toml

* Update to Python 3.13 and anaconda-client v1.13.0.
- c.f. https://github.com/anaconda/anaconda-client/releases/tag/1.13.0
* Update project version to v0.6.2.
I'm intentionally making this on a branch in the main project repo and not from my fork so that the CI will run to validate the `anaconda-client` changes.
---
To keen eye reviewers who read the release notes, I'm not using the new more explicit CLI API given it is broken: https://github.com/anaconda/anaconda-client/issues/735

MNT: Update to anaconda-client v1.13.0 and project version v0.6.2

---

README.md

* For stability provide the commit SHA that corresponds to the `0.6.2` tag (b36e8c0c10dbcfd2e05bf95f17ef8c14fd708dbf) for users to pin to.

DOC: Update action commit SHA to the 0.6.2 tag
